module SvgOutput

#!/usr/bin/ruby
# encoding:  utf-8
# This is kanjisvg library generates svg images for Japanese Kanji
# Written by Kirill Radzikhovskyy kirillrdy@gmail.com
# Distributed under GPLv3
# 2010
#
# /* For all who want to learn */

  IMAGE_SIZE = 1000
  FAT_STROKE_WIDTH=20
  SKINNY_STROKE_WIDTH=5
  BLACK_COLOUR = '#000000'
  RED_COLOUR = '#FF0000'

  def svg_header
    string = <<-EOF
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!-- Generated by LibKanji -->
    <svg width="#{IMAGE_SIZE}" height="#{IMAGE_SIZE}" version="1.0"><g id="layer1">
    EOF
  end

  def svg_footer
    "</g></svg>"
  end

  def generate_path(stroke = [], width = FAT_STROKE_WIDTH ,color = BLACK_COLOUR)
    path=''
    for point in stroke
      path += "#{point.first},#{point.last} L "
    end
    svg_path = "<path style='fill:none;fill-rule:evenodd;stroke:#{color};stroke-width:#{width}px;stroke-linecap:round;stroke-linejoin:round;stroke-opacity:1' d='M #{path}' id='stroke' />\n "
    svg_path
  end

  def generate_paths(level)
    paths = ''
    stroke_width= FAT_STROKE_WIDTH

    strokes = KanjiStrokes.strokes[@kanji]

    for stroke in strokes

      if strokes.index(stroke)+1 == level
        paths+=generate_path(stroke,stroke_width=FAT_STROKE_WIDTH,RED_COLOUR)

        last_x= stroke.last.first
        last_y= stroke.last.last
        paths+= " <circle cx=\"#{last_x}\" cy=\"#{last_y}\" r=\"#{FAT_STROKE_WIDTH}\" fill=\"black\"/> "
        paths+= " <circle cx=\"#{last_x}\" cy=\"#{last_y}\" r=\"#{SKINNY_STROKE_WIDTH}\" fill=\"yellow\"/> "
        stroke_width = SKINNY_STROKE_WIDTH
      else
        paths+=generate_path(stroke,stroke_width)
      end
    end
    paths
  end

  def save_all_levels(dir='')
    levels = number_of_strokes
    for level in 1..(levels) do
      save_to_file(level,dir)
    end
  end

  def to_svg(level )
    svg_header+generate_paths(level)+svg_footer 
  end

  def save_to_file(level,dir='')
    if level<10
      prefix = '0'+level.to_s
    else 
      prefix = level.to_s
    end
    File.open(dir+@kanji+"_"+prefix+'.svg','w') do |file|
      file.write(to_svg(level))
    end
  end


end
