require_relative 'libkanji/dictionary'
require_relative 'libkanji/sentence'
require_relative 'libkanji/conjugations'
require_relative 'libkanji/dictionary_word'
require_relative 'libkanji/sentence_word'
require_relative 'libkanji/libkanji_helper.rb'
